config/routes.rb
PET::Application.routes.draw do

  devise_for :users
  resources :users, :except => [:new, :create]
  
  match "effort_logs/does_not_overlap" => "effort_logs#does_not_overlap"
  resources :effort_logs, :except => [:index, :edit, :update, :destroy]

  match 'lifecycles/home' => 'lifecycles#home'
  resources :lifecycles, :except => [:edit, :destroy, :update]

  resources :lifecycle_phases, :except => [:index, :show, :edit, :destroy]

  resources "project_phases"

  match 'deliverables/get_unit_of_measure' => 'deliverables#get_unit_of_measure'
  match 'deliverables/create_custom_deliverable_type' => 'deliverables#create_custom_deliverable_type'
  match 'deliverables/get_historical_data' => 'deliverables#get_historical_data'
  
  resources :deliverables, :except => [:index]
  resources :stock_deliverable_types, :has_many => :deliverables

  match 'projects/home' => 'projects#home'
  match 'phase_deliverables' => 'deliverables#show_phase_deliverables'
  
  resources :projects, :except => [:edit, :destroy, :update]

  root :to => "pages#dashboard"

end

app/models/deliverable.rb
# This model represents the deliverables created by the user. They are
# associated with a stock deliverable type or a custom deliverable type
# through the polymorphic association: belongs_to :assignable, :polymorphic => true
#
# Deliverables have estimated effort, estimated size, and estimated production
# rate attributes that must have this relationship:
# estimated_effort = estimated_size * estimated_production_rate

class Deliverable < ActiveRecord::Base

  has_many :effort_logs

  belongs_to :assignable, :polymorphic => true
  belongs_to :complexity

  validates :name, :presence => true
  validates :assignable_id, :presence => true
  validates :assignable_type, :presence => true

  validates :estimated_effort, :presence => true, :numericality => {:greater_than =>  0}
  validates :estimated_size, :presence => true, :numericality => {:greater_than =>  0}
  validates :estimated_production_rate, :presence => true, :numericality => {:greater_than =>  0}

  validates :complexity_id, :presence => true
  
  validate :estimations_should_be_valid

	# Return the name of the deliverable type associated with this deliverable
	def deliverable_type
		if assignable_type == "StockDeliverableType"
			StockDeliverableType.find(assignable_id).deliverable_type.name
		else
			CustomDeliverableType.find(assignable_id).name
		end
	end

  # Return the unit of measure associated with this deliverable
 	def unit_of_measure
    if assignable_type == "StockDeliverableType"
			stock_deliverable_type = StockDeliverableType.find(assignable_id)
      stock_deliverable_type.deliverable_type.unit_of_measure.unit
     else
			CustomDeliverableType.find(assignable_id).unit_of_measure.unit
		end
   end

  # Return the complexity level associated with this deliverable
 	def complexity_level
		complexity.level
  end

  # Validates that the estimations are accurate and that size * production rate = effort
  def estimations_should_be_valid
    if (estimated_effort != (estimated_size.to_f * estimated_production_rate.to_f))
      errors.add(:estimated_size, "must be equal to estimated effort / estimated production rate")
      errors.add(:estimated_production_rate, "must be equal to estimated effort / estimated size")
      errors.add(:estimated_effort, "must be equal to estimated size * estimated production rate")
    end
  end
  
  # function to get the total logged effort for this deliverable
  def logged_effort
    logged_effort = 0
    self.effort_logs.each do |log|
      logged_effort = logged_effort + log.logged_effort
    end
    logged_effort
  end

end

app/models/deliverable_type.rb
# This model represents the stock deliverable types that can be created by
# the user.

class DeliverableType < ActiveRecord::Base
  belongs_to :lifecycle_phase
  belongs_to :unit_of_measure

  has_many :stock_deliverable_types
  has_many :project_phases, :through => :stock_deliverable_types

  validates :name, :presence => true
  validates :lifecycle_phase_id, :presence => true
  validates :unit_of_measure_id, :presence => true
  
end

app/controllers/deliverables_controller.rb
# This is the controller for our deliverable resource. It sets up instance
# variables that will be used in the views. This controller provides 
# functionality for creating both stock and custom deliverables. It also
# provides functions used in deliverable-related AJAX calls that return
# JSON strings.

class DeliverablesController < ApplicationController

  before_filter :authenticate_user!, :except => []

  # GET /deliverables/1
  # GET /deliverables/1.xml
  def show
    @deliverable = Deliverable.find(params[:id])
    
    @effort_logs = @deliverable.effort_logs
    respond_to do |format|
      format.html # show.html.erb
      format.xml { render :xml => @deliverable }
    end
  end

  # GET /deliverables/show_phase_deliverables
  # Action to respond to ajax call to get the deliverables for the selected phase
  def show_phase_deliverables
    @deliverable = Deliverable.all

    respond_to do |format|
      format.json { render :json => @deliverable }
    end
  end

  # GET /deliverables/new
  # GET /deliverables/new.xml
  def new
    @deliverable = Deliverable.new
    @project_phase_id = params[:project_phase_id]

    gather_collections

    respond_to do |format|
      format.html # new.html.erb
      format.xml { render :xml => @deliverable }
    end
  end

  # GET /deliverables/1/edit
  def edit
    @deliverable = Deliverable.find(params[:id])
  end

  # POST /deliverables
  # POST /deliverables.xml
  # We are using polymorphic associations to create this deliverable
  # created through @assignable
  def create
    @assignable = find_assignable

    @deliverable = @assignable.deliverables.build(:name => params[:deliverable][:name],
                                                  :description => params[:deliverable][:description],
                                                  :estimated_effort => params[:deliverable][:estimated_effort],
                                                  :estimated_size => params[:deliverable][:estimated_size],
                                                  :estimated_production_rate => params[:deliverable][:estimated_production_rate],
                                                  :complexity_id => params[:deliverable][:complexity_id])


    respond_to do |format|
      if @deliverable.save
        format.html { redirect_to(@deliverable, :notice => 'Deliverable was successfully created.') }
        format.xml { render :xml => @deliverable, :status => :created, :location => @deliverable }
      else
        @assignable = nil
        @project_phase_id = params[:deliverable][:project_phase_id]

        gather_collections

        format.html { render :action => "new" }
        format.xml { render :xml => @deliverable.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /deliverables/1
  # PUT /deliverables/1.xml
  def update
    @deliverable = Deliverable.find(params[:id])

    respond_to do |format|
      if @deliverable.update_attributes(params[:deliverable])
        format.html { redirect_to(@deliverable, :notice => 'Deliverable was successfully updated.') }
        format.xml { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml { render :xml => @deliverable.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /deliverables/1
  # DELETE /deliverables/1.xml
  def destroy
    @deliverable = Deliverable.find(params[:id])
    
    # Save the project so that we can send the user there after deletion
    project_phase = @deliverable.assignable.project_phase
    project = project_phase.project
    
    # If there is no effort logged against this deliverable, destroy it
    if @deliverable.effort_logs.count == 0
      @deliverable.destroy
      respond_to do |format|
        format.html { redirect_to :controller => 'projects', :action => 'show',
                                  :id => project.id, :project_phase_id => project_phase.id}
        format.xml { head :ok }
      end
    
    # Otherwise, if there is effort logged against this deliverable,
    # show an error message
    else
      respond_to do |format|
        format.html { redirect_to(@deliverable, :alert => "Sorry, you cannot delete a deliverable if it has effort logged against it.") }
        format.xml { head :ok }
      end
    end
  end

  # Creates a CustomDeliverableType
  # Associates a ProjectPhase and UnitOfMeasure to the CustomDeliverableType
  def create_custom_deliverable_type
    # we get the posted variables
    # save them to the database
    custom_deliverable_type = CustomDeliverableType.new(:name => params[:name],
                                                        :project_phase_id => params[:project_phase_id],
                                                        :unit_of_measure_id => params[:unit_of_measure_id])
    # return a json string
    respond_to do |format|
      if custom_deliverable_type.save
        format.json { render :json => {:name => custom_deliverable_type.name,
                                       :id => custom_deliverable_type.id} }
      else
        format.json { render :json => {:error => "Some errors"} }
      end
    end
  end

  # Gets the UnitOfMeasure associated with the DeliverableType
  def get_unit_of_measure
    if params[:assignable_type] == "StockDeliverableType"
			stock_deliverable_type = StockDeliverableType.find(params[:assignable_id])
      unit_of_measure_name = stock_deliverable_type.deliverable_type.unit_of_measure.unit
     else
			unit_of_measure_name = CustomDeliverableType.find(params[:assignable_id]).unit_of_measure.unit
		end
	
    # return a json string
    respond_to do |format|
      format.json { render :json => {:name => unit_of_measure_name} }
    end
  end

  # Gets the Historical data for the given deliverable type and complexity
  def get_historical_data
    return_val = []
    if params[:stock_deliverable_type_id] && params[:complexity_id]
      del_type_id = params[:stock_deliverable_type_id]
      complexity_id = params[:complexity_id]
      
      stock_deliverable_type = StockDeliverableType.find_by_id(del_type_id)
      unless stock_deliverable_type.nil?
        min_record = stock_deliverable_type.get_del_with_min_effort(complexity_id)
        avg_record = stock_deliverable_type.get_del_with_avg_effort(complexity_id)
        max_record = stock_deliverable_type.get_del_with_max_effort(complexity_id)
        
        unless min_record.nil? && avg_record.nil? && max_record.nil?
          return_val[0] = [min_record.estimated_size, min_record.estimated_production_rate, min_record.estimated_effort]
          return_val[1] = [avg_record.estimated_size, avg_record.estimated_production_rate, avg_record.estimated_effort]
          return_val[2] = [max_record.estimated_size, max_record.estimated_production_rate, max_record.estimated_effort]
        end
      end
    end
    # return a json string
    respond_to do |format|
      format.json { render :json => {:hist => return_val} }
    end
  end

  private

  # Finds a StockDeliverableType or CustomDeliverableType based on the
  # assignable_id (See Deliverable).
  # This method expects a valid stock_deliverable_type_id or a
  # custom_deliverable_type_id.
  # Copied from railscasts.com (#154-polymorphic-assocation)
  # modified to fit our needs so we can find the deliverable type
  def find_assignable
    params[:deliverable].each do |name, value|
      # (.+) extracts the substring before _deliverable_type_id
      # $1 could be "custom" or "stock"
      if name =~ /(.+)_deliverable_type_id$/
        return ($1+"_deliverable_type").classify.constantize.find(value)
      end
    end
    nil
  end

  # This method is used by the DeliverablesController.new and
  # DeliverablesController.edit to gather the collections that need
  # to be displayed on the associated forms.
  def gather_collections
    project_phase = ProjectPhase.find(@project_phase_id)

    # TODO: Add the custom deliverables into this list

    # Encode the id as stock_<id>
    sdt = project_phase.stock_deliverable_types unless project_phase.nil?
    @stock_deliverable_types = sdt.map {|s| [s.deliverable_type.name, "stock_" + s.id.to_s]}

    @complexities = Complexity.all
    @units_of_measure = UnitOfMeasure.all
  end
end

app/helpers/deliverables_helper.rb
# Helper class for deliverables
module DeliverablesHelper

  # Gets the project associated with the deliverable
  def get_project
     @deliverable.assignable.project_phase.project
  end

  # Gets the project phase id string associated with the deliverable
  def get_project_phase_id_string
     @deliverable.assignable.project_phase.id.to_s
  end

  # Gets the user associated with the effort log
  def get_effort_log_user(effort_log)
    if !effort_log.nil? && !effort_log.user.nil?
      effort_log.user.email
    else
      "Deleted User"
    end
  end
end

app/views/deliverables/edit.html.erb
<h1>Editing deliverable</h1>
<% content_for(:head) do %>
    <%= javascript_include_tag "deliverable_estimations", "jquery.validate.min", "deliverable_validation" %>
<% end %>

<%= form_for(@deliverable,:html => {:id  =>  "deliverable_form"}) do |f| %>
    <% if @deliverable.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@deliverable.errors.count, "error") %> prohibited this deliverable from being saved:</h2>

          <ul>
            <% @deliverable.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <br/>

    <div class="clearfix">
      <%= f.label :name %>
      <div class="input">
        <%= f.text_field :name, :class=>"xlarge" %>
      </div>
    </div>
    <div class="clearfix">
      <%= f.label :description %>
      <div class="input">
        <%= f.text_area :description, :size => "40x10", :class=>"xlarge" %>
      </div>
    </div>
    <div class="clearfix">
      <%= label_tag "Deliverable Type" %>
      <div class="input">
        <%= @deliverable.deliverable_type %>
      </div>

    </div>
    <div class="clearfix">
      <%= f.label :estimated_size %>
      <div id="estimated_size_input_id" class="input">
        <%= f.text_field :estimated_size, :class=>"xlarge" %>
        <%= @deliverable.unit_of_measure %>
      </div>
    </div>
    <div class="clearfix">
      <%= f.label :estimated_production_rate %>
      <div id="estimated_production_rate_input_id" class="input">
        <%= f.text_field :estimated_production_rate, :class=>"xlarge" %>
        hours/<%= @deliverable.unit_of_measure.singularize %>
      </div>
    </div>
    <div class="clearfix">
      <%= f.label :estimated_effort %>
      <div id="estimated_effort_input_id" class="input">
        <%= f.text_field :estimated_effort, :class=>"xlarge" %> hours
      </div>
    </div>
    <br/>
    <div class="input">
      <%= f.submit "Update Deliverable", :class => "btn primary" %>
      &nbsp;
      <%= link_to 'Cancel', @deliverable, :class => "btn danger" %>
    </div>
<% end %>

app/views/deliverables/index.html.erb
<h1>Listing deliverables</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Estimated size</th>
    <th>Estimated production rate</th>
    <th>Estimated effort</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @deliverables.each do |deliverable| %>
  <tr>
    <td><%= deliverable.name %></td>
    <td><%= deliverable.description %></td>
    <td><%= deliverable.estimated_size %></td>
    <td><%= deliverable.estimated_production_rate %></td>
    <td><%= deliverable.estimated_effort %></td>
    <td><%= link_to 'Show', deliverable %></td>
    <td><%= link_to 'Edit', edit_deliverable_path(deliverable) %></td>
    <td><%= link_to 'Destroy', deliverable, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Deliverable', new_deliverable_path %>

app/views/deliverables/new.html.erb
<h1>New deliverable</h1>

<% content_for(:head) do %>
    <%= javascript_include_tag "deliverable_utilities", "historical_data", "new_deliverable", "deliverable_estimations", "jquery.validate.min", "deliverable_validation" %>
<% end %>

<%= form_for @deliverable, :html => {:id  =>  "deliverable_form"} do |f| %>
  <% if @deliverable.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deliverable.errors.count, "error") %> prohibited this deliverable from being saved:</h2>

      <ul>
      <% @deliverable.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <br/>

  <div class="clearfix">
    <%= f.label :name %>
	<div class="input">
		<%= f.text_field :name, :class=>"xlarge" %>
	</div>
  </div>
  <div class="clearfix">
    <%= f.label :description %>
	<div class="input">
    	<%= f.text_area :description, :size => "40x10", :class=>"xlarge" %>
	</div>
  </div>
  <div class="clearfix">
		<%= f.label :deliverable_type %>
		<div class="input">
			<%= f.select :assignable_id, @stock_deliverable_types %>
		</div>
	  <div id="deliverable_type_id">
	  </div>
  </div>

  <div class="clearfix">
  	<p id="deliverable_unit_of_measure">
			<%= f.label :unit_of_measure %>
			<span id="unit_of_measure_name"></span>
		</p>
  </div>

  <div class="clearfix">
  	<%= f.label :complexity %>
		<div class="input">
			<%= f.select :complexity_id, @complexities.map {|c| [c.level, c.id]} %>
		</div>
		<div id="view_historical_data_container">
		  <a href="javascript:void(0);" id="view_historical_data">Show historical data</a>
		</div>
  </div>
  
  <div id="historical_data_table" class="clearfix" style="display:none">
    <table class="condensed-table show_all">
      <thead>
        <tr>
          <th></th>
          <th>Size</th>
          <th>Rate</th>
          <th>Effort</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Minimum</td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>Average</td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>Maximum</td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
      </tbody>
    </table>
  </div>
  
  <div class="clearfix">
    <%= f.label :estimated_size %>
	<div id="estimated_size_input_id" class="input">
    	<%= f.text_field :estimated_size, :class=>"xlarge" %>
	</div>
  </div>
  <div class="clearfix">
    <%= f.label :estimated_production_rate %>
	<div id="estimated_production_rate_input_id" class="input">
    	<%= f.text_field :estimated_production_rate, :class=>"xlarge" %>
	</div>
  </div>
  <div class="clearfix">
    <%= f.label :estimated_effort %>
	<div id="estimated_effort_input_id" class="input">
        <%= f.text_field :estimated_effort, :class=>"xlarge" %>
	</div>
  </div>

  <%= f.hidden_field :project_phase_id, :value => @project_phase_id %>
  <div class="input">
    <%= f.submit "Create Deliverable", :class => "btn primary" %>
    &nbsp;
    <%= link_to 'Cancel', request.referer, :class => "btn danger" %>
  </div>
<% end %>

<div id="dialog" title="Create Deliverable Type">
      <div class="field dialog_field">
      <p>
     <%= label_tag 'Name' %>
     <%= text_field_tag 'name' %>
         </p>
        </div>
      <div class="field dialog_field">
      <%= label_tag 'Unit of Measure' %>
	  <%  unless @units_of_measure.nil?
		   units_of_measure_array = @units_of_measure.collect {|u| [u.unit, u.id] }
		 else
		   units_of_measure_array = []
		 end %>
      <%= select_tag 'unit_of_measure_id', options_for_select(units_of_measure_array) %>
      </div>
</div>

app/views/deliverables/show.html.erb
<h1>
  <%= @deliverable.name %>
</h1>

<p class="description">
  <%= @deliverable.description %>
</p>

<p>
  <b>Deliverable Type:</b>
  <%= @deliverable.deliverable_type %>
</p>

<p>
  <b>Estimated size:</b>
  <%= @deliverable.estimated_size %>
  <%= @deliverable.unit_of_measure %>
</p>

<p>
  <b>Estimated production rate:</b>
  <%= @deliverable.estimated_production_rate %>
  hours/<%= @deliverable.unit_of_measure.singularize %>
</p>

<p>
  <b>Estimated effort:</b>
  <%= @deliverable.estimated_effort %> hours
</p>

<p>
  <b>Logged effort:</b>
  <%= sprintf('%.2f', @deliverable.logged_effort) %> hours
</p>
<br />

<%= link_to 'Modify', edit_deliverable_path(@deliverable), :class => 'btn primary' %>
<%= link_to 'Delete', @deliverable, :confirm => 'Are you sure?', :method => :delete, :class => 'btn danger' %>
<%= link_to 'Return to Project', project_path(get_project)+"?project_phase_id="+get_project_phase_id_string, :class => 'btn' %>

<br />
<br />

<h3>Effort logs</h3>
<table>
  <tr>
    <th>User email</th>
    <th>Logged effort (hours)</th>
    <th></th>
  </tr>

  <% unless @effort_logs.nil? %>
      <% @effort_logs.each do |effort_log| %>
          <tr>
            <td><%= get_effort_log_user(effort_log) %></td>
            <td><%= sprintf('%.2f', effort_log.logged_effort) %></td>
            <td><%= link_to 'More details', effort_log %></td>
          </tr>
      <% end %>
  <% end %>
</table>

<%= link_to 'Log Effort', new_effort_log_path(:deliverable_id => @deliverable), :class => 'btn primary' %>