config/routes.rb
PET::Application.routes.draw do

  devise_for :users
  resources :users, :except => [:new, :create]
  
  match "effort_logs/does_not_overlap" => "effort_logs#does_not_overlap"
  resources :effort_logs, :except => [:index, :edit, :update, :destroy]

  match 'lifecycles/home' => 'lifecycles#home'
  resources :lifecycles, :except => [:edit, :destroy, :update]

  resources :lifecycle_phases, :except => [:index, :show, :edit, :destroy]

  resources "project_phases"

  match 'deliverables/get_unit_of_measure' => 'deliverables#get_unit_of_measure'
  match 'deliverables/create_custom_deliverable_type' => 'deliverables#create_custom_deliverable_type'
  match 'deliverables/get_historical_data' => 'deliverables#get_historical_data'
  
  resources :deliverables, :except => [:index]
  resources :stock_deliverable_types, :has_many => :deliverables

  match 'projects/home' => 'projects#home'
  match 'phase_deliverables' => 'deliverables#show_phase_deliverables'
  
  resources :projects, :except => [:edit, :destroy, :update]

  root :to => "pages#dashboard"

end

app/views/pages/dashboard.html.erb
<div class="content-box dashboard-box">
  <div class="content-box-title">
    PROJECTS
    <%= link_to "See all", projects_path %>
  </div>
  <div class="content-box-body">
    <table class="condensed-table show_all">
      <% @projects.each do |project| %>
          <tr>
            <td>
              <%= link_to project.name, project %>
              <br />
              <%= project.description %>
               <br />
              [<i><%= project.estimated_effort %> hours</i>]
            </td>
          </tr>
      <% end %>
    </table>
    <%= link_to "Create Project", new_project_path, :class => "btn primary" %>
  </div>
</div>

<div class="content-box dashboard-box">
  <div class="content-box-title">
    LIFECYCLES
    <%= link_to "See all", lifecycles_path %>
  </div>
  <div class="content-box-body">
  <table class="condensed-table show_all">
    <% @lifecycles.each do |lifecycle| %>
        <tr>
          <td>
            <%= link_to lifecycle.name, lifecycle %>
            <br />
            <%= lifecycle.description %>
          </td>
        </tr>
    <% end %>
  </table>
    <% if @current_user.role?(:admin) %>
        <%= link_to "Create Lifecycle", new_lifecycle_path, :class => "btn primary" %>
    <% end %>
  </div>
</div>

<% if can? :read, @users %>
<div class="content-box dashboard-box">
  <div class="content-box-title">
    USERS
    <%= link_to "See all", users_path %>
  </div>
  <div class="content-box-body">
  <table class="condensed-table show_all">
    <% @users.each do |user| %>
        <tr>
          <td>
            <%= link_to user.email, user %>
          </td>
        </tr>
    <% end %>
  </table>
  </div>
</div>
<% end %>
<br />