config/routes.rb
PET::Application.routes.draw do

  devise_for :users
  resources :users, :except => [:new, :create]
  
  match "effort_logs/does_not_overlap" => "effort_logs#does_not_overlap"
  resources :effort_logs, :except => [:index, :edit, :update, :destroy]

  match 'lifecycles/home' => 'lifecycles#home'
  resources :lifecycles, :except => [:edit, :destroy, :update]

  resources :lifecycle_phases, :except => [:index, :show, :edit, :destroy]

  resources "project_phases"

  match 'deliverables/get_unit_of_measure' => 'deliverables#get_unit_of_measure'
  match 'deliverables/create_custom_deliverable_type' => 'deliverables#create_custom_deliverable_type'
  match 'deliverables/get_historical_data' => 'deliverables#get_historical_data'
  
  resources :deliverables, :except => [:index]
  resources :stock_deliverable_types, :has_many => :deliverables

  match 'projects/home' => 'projects#home'
  match 'phase_deliverables' => 'deliverables#show_phase_deliverables'
  
  resources :projects, :except => [:edit, :destroy, :update]

  root :to => "pages#dashboard"

end

app/models/lifecycle.rb
# This model represents the pre-defined lifecycles. Many projects can be
# associated with a lifecycle, and each lifecycle has many lifecycle phases.

class Lifecycle < ActiveRecord::Base
 has_many :projects
 has_many :lifecycle_phases, :order=>"sequence_number asc"

 validates :name, :presence => true
end

app/controllers/lifecycles_controller.rb
# This is the controller for our lifecycle resource. It sets up instance
# variables that will be used in the views. This controller provides 
# functionality for the CRUD operations of our Lifecycle model.

class LifecyclesController < ApplicationController

  before_filter :authenticate_user!, :except => []
  before_filter :accessible_roles, :only => [:new, :create]
  load_and_authorize_resource

  # GET /lifecycles
  # GET /lifecycles.xml
  def index
    @lifecycles = Lifecycle.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @lifecycles }
    end
  end

  # GET /lifecycles/home
  def home
  end

  # GET /lifecycles/1
  # GET /lifecycles/1.xml
  def show
    #@lifecycle = Lifecycle.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @lifecycle }
    end
  end

  # GET /lifecycles/new
  # GET /lifecycles/new.xml
  def new
    #@lifecycle = Lifecycle.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @lifecycle }
    end
  end

  # GET /lifecycles/1/edit
  # def edit
  #   #@lifecycle = Lifecycle.find(params[:id])
  # end

  # POST /lifecycles
  # POST /lifecycles.xml
  def create
    @lifecycle = Lifecycle.new(params[:lifecycle])

    respond_to do |format|
      if @lifecycle.save
        format.html { redirect_to(@lifecycle, :notice => 'Lifecycle was successfully created.') }
        format.xml  { render :xml => @lifecycle, :status => :created, :location => @lifecycle }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @lifecycle.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /lifecycles/1
  # PUT /lifecycles/1.xml
  # def update
  #   #@lifecycle = Lifecycle.find(params[:id])
  # 
  #   respond_to do |format|
  #     if @lifecycle.update_attributes(params[:lifecycle])
  #       format.html { redirect_to(@lifecycle, :notice => 'Lifecycle was successfully updated.') }
  #       format.xml  { head :ok }
  #     else
  #       format.html { render :action => "edit" }
  #       format.xml  { render :xml => @lifecycle.errors, :status => :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /lifecycles/1
  # DELETE /lifecycles/1.xml
  # def destroy
  #   @lifecycle = Lifecycle.find(params[:id])
  #   @lifecycle.destroy
  # 
  #   respond_to do |format|
  #     format.html { redirect_to(lifecycles_url) }
  #     format.xml  { head :ok }
  #   end
  # end
end

app/helpers/lifecycles_helper.rb
# Helper class for lifecycles

module LifecyclesHelper
end

app/views/lifecycles/_form.html.erb
<% content_for(:head) do %>
    <%= javascript_include_tag "jquery.validate.min", "lifecycle_validation" %>
<% end %>

<%= form_for(@lifecycle, :html => {:id => "lifecycle_form"}) do |f| %>
    <% if @lifecycle.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@lifecycle.errors.count, "error") %> prohibited this lifecycle from being saved:</h2>

          <ul>
            <% @lifecycle.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="clearfix">
      <%= f.label :name %>
      <div class="input">
        <%= f.text_field :name, :class=>"xlarge" %>
      </div>
    </div>
    <div class="clearfix">
      <%= f.label :description %>
      <div class="input">
        <%= f.text_area :description, :size => "40x10", :class=>"xlarge" %>
      </div>
    </div>
    <div class="input">
      <%= f.submit "Create", :class => "btn primary" %>
      <%= link_to 'Cancel', lifecycles_path, :class => "btn danger" %>
    </div>
<% end %>

app/views/lifecycles/edit.html.erb
<h1>Editing lifecycle</h1>

<%= render 'form' %>

<%= link_to 'Show', @lifecycle %> |
<%= link_to 'Back', lifecycles_path %>

app/views/lifecycles/home.html.erb
<div id="lifecycle_home" class="home">
	<p><%= link_to 'View Lifecycles', lifecycles_path, :id => "view_lifecycles" %></p><br /><br />
</div>

app/views/lifecycles/index.html.erb
<h1>All lifecycles</h1>

<table class="condensed-table show_all">
<% @lifecycles.each do |lifecycle| %>
  <tr>
    <td><%= link_to lifecycle.name, lifecycle %></td>
    <td><%= lifecycle.description %></td>
  </tr>
<% end %>
</table>

<% if @current_user.role?(:admin) %>
    <%= link_to "Create Lifecycle", new_lifecycle_path, :class => "btn primary" %>
<% end %>

app/views/lifecycles/new.html.erb
<h1>New lifecycle</h1>

<%= render 'form' %>

app/views/lifecycles/show.html.erb
<h1><%= @lifecycle.name %></h1>

<% content_for(:head) do %>
    <%= javascript_include_tag "lifecycle" %>
<% end %>

<p class="description">
  <%= @lifecycle.description %>
</p>


<h3>Lifecycle Phases</h3>
<% if @lifecycle.projects.count == 0 && @current_user.role?(:admin) %>
    <div id="lifecycle_helper_text">(Drag and drop to reorder lifecycle phases)</div>
<% end %>

<br/>

<% if @lifecycle.projects.count == 0 && @current_user.role?(:admin)%>

    <div id="sequence_numbers">
       <ul class="phase_sortable">
         <% @lifecycle.lifecycle_phases.each_with_index do |phase, index| %>
            <li id = "phases_<%=phase.id%>" class="ui-state-default">
                <%=(index+1)%>.
            </li>
        <% end %>
      </ul>
    </div>

    <div id="lifecycle_phase_list">
      <ul id="sortable" class="phase_sortable">
        <% @lifecycle.lifecycle_phases.each_with_index do |phase, index| %>
            <li id = "phases_<%=phase.id%>" class="ui-state-default">
              <span class="ui-icon ui-icon-arrowthick-2-n-s"></span>
              <div title="<%= phase.description %>">
                <%= phase.name %>
              </div>
            </li>
        <% end %>
      </ul>
    </div>
<% else %>

    <table border="0" id="lifecycle_phases">
      <thead>
      <tr>
        <th>Sequence<br/>Number</th>
        <th>Name</th>
        <th>Description</th>
      </tr>
      </thead>
      <tbody>

      <% @lifecycle.lifecycle_phases.each do |phase| %>
          <tr>
            <td><%= phase.sequence_number %></td>
            <td><%= phase.name %></td>
            <td><%= phase.description %></td>
          </tr>
      <% end %>

      </tbody>
    </table>
<% end %>

<div style="display:none" id="lifecycle_id">
  <%= @lifecycle.id %>
</div>
<br />

<div id="lifecycle_buttons">
<% if @lifecycle.projects.count == 0 && @current_user.role?(:admin) %>
    <%= link_to "Create Lifecycle Phase", new_lifecycle_phase_path(:lifecycle_id => @lifecycle.id), :class => "btn primary" %>
<% end %>

<%= link_to 'Return to Lifecycles', lifecycles_path, :class => "btn" %>
</div>